--liquibase formatted sql

-- Baseline: the schema as it existed before migrations were introduced,
-- originally auto-created by Hibernate (ddl-auto=update) and captured from
-- the live dev DB on 2026-08-15.
--
-- The sql-check preconditions with onFail:MARK_RAN make the dev DB (which
-- already has these tables) skip this changeset, while a fresh database
-- executes it. CAUTION: on an existing DB, rolling back a MARK_RAN changeset
-- would drop tables that Liquibase never created — don't do that.

--changeset tvpirate:0001-baseline-users
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'users'
--comment: baseline users table
CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(255) NOT NULL UNIQUE,
    email varchar(255) UNIQUE,
    provider varchar(255) NOT NULL CHECK (provider IN ('GUEST', 'GOOGLE')),
    created_at timestamp(6) with time zone NOT NULL
);
--rollback DROP TABLE users;

--changeset tvpirate:0001-baseline-refresh-tokens
--preconditions onFail:MARK_RAN onError:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'refresh_tokens'
--comment: baseline refresh_tokens table (stores SHA-256 hashes, never raw tokens)
CREATE TABLE refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash varchar(255) NOT NULL UNIQUE,
    user_id bigint NOT NULL REFERENCES users(id),
    expires_at timestamp(6) with time zone NOT NULL,
    created_at timestamp(6) with time zone NOT NULL
);
--rollback DROP TABLE refresh_tokens;
