--liquibase formatted sql

--changeset tvpirate:0003-watch-progress
--comment: per-user playback position for resume; movie rows carry NULL season/episode
CREATE TABLE watch_progress (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    tmdb_id bigint NOT NULL,
    media_type varchar(255) NOT NULL CHECK (media_type IN ('movie', 'tv')),
    season_number int,
    episode_number int,
    progress_seconds int NOT NULL,
    duration_seconds int,
    updated_at timestamp(6) with time zone NOT NULL,
    CHECK (media_type = 'tv' OR (season_number IS NULL AND episode_number IS NULL))
);
-- Partial unique indexes: Postgres' default NULLS DISTINCT would let a plain
-- unique index pass duplicate movie rows (NULL, NULL). One index per shape.
CREATE UNIQUE INDEX uq_watch_progress_movie ON watch_progress (user_id, tmdb_id) WHERE season_number IS NULL;
CREATE UNIQUE INDEX uq_watch_progress_tv ON watch_progress (user_id, tmdb_id, season_number, episode_number) WHERE season_number IS NOT NULL;
--rollback DROP TABLE watch_progress;
