--liquibase formatted sql

--changeset tvpirate:0004-favourites
--comment: server-backed favourites (heart button); media_type keeps the two TMDB id namespaces apart
CREATE TABLE favourites (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    tmdb_id bigint NOT NULL,
    media_type varchar(255) NOT NULL CHECK (media_type IN ('movie', 'tv')),
    created_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT uq_favourites_user_title UNIQUE (user_id, tmdb_id, media_type)
);
--rollback DROP TABLE favourites;
